[install]
is_configured = 0
state = enabled
build = 50

[launcher]
author = Eric Cobbs
description = Telemetry-aware detection engineering intelligence for Splunk Enterprise and Splunk Cloud, with optional Enterprise Security enhancements.
version = 0.1.43

[package]
id = splunk_detection_engineering_intelligence
check_for_updates = 0

[ui]
is_visible = 1
label = Detection Engineering Intelligence
