[script:dei_health]
match = /dei/v1/health
handler = dei.api.health_handler.HealthHandler
methods = GET
requireAuthentication = true
output_modes = json
passPayload = true

[script:dei_capabilities]
match = /dei/v1/capabilities
handler = dei.api.capabilities_handler.CapabilitiesHandler
methods = GET
requireAuthentication = true
output_modes = json
passPayload = true
