[script:dei_health]
match = /dei/v1/health
script = dei_health_rest.py
scripttype = persist
python.version = python3
handler = dei_health_rest.HealthApplication
methods = GET
requireAuthentication = true
output_modes = json
passPayload = true

[script:dei_capabilities]
match = /dei/v1/capabilities
script = dei_capabilities_rest.py
scripttype = persist
python.version = python3
handler = dei_capabilities_rest.CapabilitiesApplication
methods = GET
requireAuthentication = true
output_modes = json
passPayload = true

[script:dei_recommendations]
match = /dei/v1/recommendations
script = dei_recommendations_rest.py
scripttype = persist
python.version = python3
handler = dei_recommendations_rest.RecommendationsApplication
methods = POST
requireAuthentication = true
output_modes = json
passPayload = true

[script:dei_storage]
match = /dei/v1/storage
script = dei_storage_rest.py
scripttype = persist
python.version = python3
handler = dei_storage_rest.StorageApplication
methods = GET,POST
requireAuthentication = true
output_modes = json
passPayload = true
