#!/usr/bin/env python3
"""Build the browser-safe detection catalog shipped with every DEI package."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKS = ROOT / "app" / "knowledgepacks"
OUTPUT = ROOT / "app" / "appserver" / "static" / "dei_detection_library_v1.js"


def build_library() -> list[dict[str, object]]:
    """Return the same definitions exposed by the capabilities service."""
    detections: list[dict[str, object]] = []
    for manifest_path in sorted(PACKS.glob("*/manifest.json")):
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        for relative_path in manifest["detection_files"]:
            definitions = json.loads(
                (manifest_path.parent / relative_path).read_text(encoding="utf-8")
            )
            for definition in definitions:
                entry = dict(definition)
                entry["detection_id"] = str(entry.pop("id", ""))
                entry["knowledge_pack"] = manifest["name"]
                detections.append(entry)
    return sorted(
        detections,
        key=lambda item: (str(item.get("name", "")), str(item["detection_id"])),
    )


def main() -> None:
    """Write a deterministic, dependency-free browser asset."""
    payload = json.dumps(build_library(), separators=(",", ":"), ensure_ascii=False)
    OUTPUT.write_text(
        "/* Generated by tools/build_static_detection_library.py. */\n"
        f"window.DEIDetectionLibrary=Object.freeze({payload});\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
